### ISSUE TITLE
Errors on startup

### ISSUE THREAD

**Issue by in4matix** [ivan-hc/WPS-Office-appimage#1]
Seems to be working good, but getting these errors on startup:
![Screenshot from 2024-02-02 23-01-57](https://github.com/ivan-hc/WPS-Office-appimage/assets/62904593/538a62b2-abff-489c-ad4c-375f2aef1114)
![Screenshot from 2024-02-02 23-02-23](https://github.com/ivan-hc/WPS-Office-appimage/assets/62904593/61c69b3f-64cd-42df-9e96-dd924d51d7ee)

Maybe I am not using correct command or option?

E.g. `$ ./WPS-Office_11.1.0.11711-MUI-x86_64.AppImage wps`

Can you add base (the main one to choose: recent, templates, or which app to open?

**Comment by ivan-hc** [comment]
The error you see is due to the AppRun:
```
#!/usr/bin/env bash
HERE="$(dirname "$(readlink -f "${0}")")"
export LD_LIBRARY_PATH="$HERE/usr/lib":"$HERE/usr/lib/x86_64-linux-gnu":"$HERE/lib":"$HERE/lib/x86_64-linux-gnu":"$HERE/lib64":$LD_LIBRARY_PATH
case $1 in
	'')		echo -e "\n USAGE:	command [ARGUMENT]"
			echo -e '\n Where [ARGUMENT] is one between "et" "wpp" "wps" and "wpspdf"\n';;
	'et')		"$HERE/usr/bin/et" "$@";;
	'wpp')		"$HERE/usr/bin/wpp" "$@";;
	'wps')		"$HERE/usr/bin/wps" "$@";;
	'wpspdf')	"$HERE/usr/bin/wpspdf" "$@";;
esac
```
Where "$0" is the ./*.AppImage and "$1" is one between "et" "wpp" "wps" and "wpspdf".

That said, seems that WPS does not recognize that the option of the AppRun is just an option, not a file. So we get this error.

I've spent an entire afternoon to fix this without success.

If you have another solution, you're wellcome.

Try to rebuild the AppImage on your PC using the script [wps-office.sh](https://github.com/ivan-hc/WPS-Office-appimage/blob/main/wps-office.sh) and tell me what you discover.

PS: I'd like to keep the selection via command line, maybe I can put the selector in " *) "... but I'm not an expert of this application. This is the first time I opened it.

**Comment by ivan-hc** [comment]
This new AppRun will launch the "startup center" by double clicking on it

```
#!/usr/bin/env bash
HERE="$(dirname "$(readlink -f "${0}")")"
export QT_FONT_DPI=96
export LD_LIBRARY_PATH="$HERE/usr/lib":"$HERE/usr/lib/x86_64-linux-gnu":"$HERE/lib":"$HERE/lib/x86_64-linux-gnu":"$HERE/lib64":$LD_LIBRARY_PATH
case $1 in
	'')
		"$HERE/opt/kingsoft/wps-office/office6/wpsoffice";;		
	'et')
		"$HERE/usr/bin/et" "$@";;
	'wpp')
		"$HERE/usr/bin/wpp" "$@";;
	'wps')
		"$HERE/usr/bin/wps" "$@";;
	'wpspdf')
		"$HERE/usr/bin/wpspdf" "$@";;
	'help'|'-h'|'--help')
		echo -e "\n USAGE:	command [ARGUMENT]"
		echo -e '\n Where [ARGUMENT] is one between "et" "wpp" "wps" and "wpspdf"\n';;
esac
```
and DPI has been improved

![Istantanea_2024-02-03_01-57-47](https://github.com/ivan-hc/WPS-Office-appimage/assets/88724353/6df539af-8851-4dfc-9543-50fe8206cb50)

all is left is to get rid of the annoynd message at startup.

**Comment by ivan-hc** [comment]
I've just added and patched the *prometheus.desktop file to made it available if installed via AM or AppMan

https://github.com/ivan-hc/AM-Application-Manager/commit/52bab81b86976732c08957f734eb77146326106c

Now all the work is on the AppImage itself, we need to get rid of that annoyng message.

**Comment by in4matix** [comment]
When using the "startup center" the annoying message is gone, but when clicking on a new tab, it is supposed to give you the option to select either a new writer, et, and presentation document, but it automatically opens just a new writer document. These are the messages in Terminal:
```
daniel@dkpc:~/Downloads$ ./WPS-Office_11.1.0.11711-MUI-x86_64.AppImage
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
the error = [libproviders.so: cannot open shared object file: No such file or directory]
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
the error = [libproviders.so: cannot open shared object file: No such file or directory]
QObject::killTimer: Timers cannot be stopped from another thread
QObject::killTimer: Timers cannot be stopped from another thread
QObject::~QObject: Timers cannot be stopped from another thread
QObject::~QObject: Timers cannot be stopped from another thread
daniel@dkpc:~/Downloads$ ./WPS-Office_11.1.0.11711-MUI-x86_64.AppImage
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
the error = [libproviders.so: cannot open shared object file: No such file or directory]
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
the error = [libproviders.so: cannot open shared object file: No such file or directory]
QObject::killTimer: Timers cannot be stopped from another thread
QObject::killTimer: Timers cannot be stopped from another thread
QObject::~QObject: Timers cannot be stopped from another thread
QObject::~QObject: Timers cannot be stopped from another thread
daniel@dkpc:~/Downloads$ ./WPS-Office_11.1.0.11711-MUI-x86_64.AppImage et
```
When using with [ARGUMENT] , e.g. "et" , no errors in terminal, but the annoying message is displayed.

I wish I could be of more help, but my coding knowledge at this stage is zero...

**Comment by ivan-hc** [comment]
If I don't know much on how this program shows the messages, I cannot be of any help too.

In the AppRun I have tried to launch the scripts in /usr/bin or directly the binaries in /opt... nothing changes. Also binaries in /opt seems not to include basic options like --help, -h, --version, -v or anything like this.

You should understand the mechanism of the binaries and how to made them work to launch the single parts of the program, what files and libraries are called first....

About Wayland errors, it seems that the host or the guest have a missing library, libproviders.so

About the message "QObject::killTimer", I don't know what it means, but until the app works, for me its ok to ignore it.

If I have enough time, I'll try to include a wrapper in the AppImage to stop the annoyng message.

**Comment by ivan-hc** [comment]
I've solved, it was enough to change "$@" with "$2".

Now all the annoyng messages are disappeared.

Also improved the options, including the single arguments and the version of WPS.

Also you should be able to opend documents from command line using the syntax `command [ARGUMENT] /path/to/file`

Just launched the github action, the AppImage will be available soon.

ACTION: https://github.com/ivan-hc/WPS-Office-appimage/actions/runs/7768943942

DOWNLOAD: https://github.com/ivan-hc/WPS-Office-appimage/releases/tag/continuous

**Comment by in4matix** [comment]
Thank you very much!! I figured out how to get All-in-one mode.
1. Start AppImage without argument.
2. Open settings, top right
![1](https://github.com/ivan-hc/WPS-Office-appimage/assets/62904593/2594531d-59cd-4287-8e04-de251f53ef1f)
3. Select "Change window manage mode"
4. Select "All-in-one mode"
![2](https://github.com/ivan-hc/WPS-Office-appimage/assets/62904593/bd505d30-c515-40c0-b2c3-13ea7d9d3393)
5. Restart App
6. Now when you click on tab, can choose type of document
![3](https://github.com/ivan-hc/WPS-Office-appimage/assets/62904593/b42f1ae4-18ad-4925-a011-a3b6d2715ce4)
